### ISSUE TITLE
Reference implementation language selection

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/fuzzy-encryption#1]
Decide on which language to develop the reference implementation in. Initial thoughts: Rust, TypeScript, or Python?

**Comment by OR13** [comment]
+1 for Rust, TypeScript bindings around a wasm module for JS ecosystem.

We need the crypto primitives to be documented on this issue, in order to figure out which language would be easiest

**Comment by tim-stasse** [comment]
Hi, hope you don't mind me chiming in.

How detailed of a reference implementation are you planning? Will it simply be an algorithmic demonstration, or a usage of?

**Comment by kdenhartog** [comment]
+1 to rust for greater memory control, especially like the ability to overwrite memory of secrets.

I'd suspect if we wrote in rust though, there probably won't be as many reimplementations because it will be possible to just consume the reference implementation in a variety of languages.

Is that something we'd want?

**Comment by csuwildcat** [comment]
We have a first test implementation in Python, and the C++ final implementation is on the way (projecting early Nov)
